	module CARD_TEXT
map:
	dw BRICK_SHORTAGE
	dw LUCKY_CACHE
	dw FRIENDLY_TERRAIN
	dw MINERS
	dw MOTHER_LODE
	dw DWARVEN_MINERS
	dw WORK_OVERTIME
	dw COPPING_THE_TECH
	dw BASIC_WALL
	dw STURDY_WALL
	dw INNOVATIONS
	dw FOUNDATIONS
	dw TREMORS
	dw SECRET_ROOM
	dw EARTHQUAKE
	dw BIG_WALL
	dw COLLAPSE!
	dw NEW_EQUIPMENT
	dw STRIP_MINE
	dw REINFORCED_WALL

data:

BRICK_SHORTAGE:
	db "BRICK SHORTAGE",#0A
	db "ALL PLAYERS LOSE",#0A,"",#09,"8 BRICKS.",#00
LUCKY_CACHE:
	db "LUCKY CACHE",#0A
	db "+2 BRICKS, +2 GEMS, PLAY AGAIN.",#00
FRIENDLY_TERRAIN:
	db "FRIENDLY TERRAIN",#0A
	db "null",#00
MINERS:
	db "MINERS",#0A
	db "null",#00
MOTHER_LODE:
	db "MOTHER LODE",#0A
	db "IF",#0A,"QUARRY < ENEMY",#0A,"QUARRY,",#0A,"",#FF,"+2 QUARRY.",#0A,"ELSE,",#0A,"",#FF,"+1 QUARRY.",#00
DWARVEN_MINERS:
	db "DWARVEN MINERS",#0A
	db "+4 WALL,",#0A,"",#FF,"+1 QUARRY.",#00
WORK_OVERTIME:
	db "WORK OVERTIME",#0A
	db "",#09,"+5 WALL.",#0A,"",#0A,"",#FF,"YOU LOSE SIX",#0A,"",#09,"",#FF,"GEMS.",#00
COPPING_THE_TECH:
	db "COPPING THE TECH",#0A
	db "IF",#0A,"QUARRY < ENEMY",#0A,"",#09,"QUARRY,",#0A,"QUARRY = ENEMY",#0A,"",#09,"QUARRY.",#00
BASIC_WALL:
	db "BASIC WALL",#0A
	db "",#09,"+3 WALL.",#00
STURDY_WALL:
	db "STURDY WALL",#0A
	db "",#09,"+4 WALL.",#00
INNOVATIONS:
	db "INNOVATIONS",#0A
	db "+1 TO ALL PLAYER'S QUARRYS, YOU GAIN 4 GEMS.",#00
FOUNDATIONS:
	db "FOUNDATIONS",#0A
	db "IF WALL = 0,",#0A,"",#FF,"+6 WALL,",#0A,"ELSE",#0A,"",#FF,"+3 WALL.",#00
TREMORS:
	db "TREMORS",#0A
	db "ALL WALLS",#0A,"TAKE 5 DAMAGE.",#0A,"",#09," PLAY AGAIN.",#00
SECRET_ROOM:
	db "SECRET ROOM",#0A
	db "",#0A,"",#0A,"",#0A,"+1 MAGIC.",#0A,"",#09,"",#FF,"PLAY AGAIN",#00
EARTHQUAKE:
	db "EARTHQUAKE",#0A
	db "",#09,"",#FF,"-1",#0A,"TO ALL PLAYER'S",#0A,"",#09,"QUARRYS.",#00
BIG_WALL:
	db "BIG WALL",#0A
	db "",#09,"+6 WALL.",#00
COLLAPSE!:
	db "COLLAPSE!",#0A
	db "",#09,"",#FE,"-1",#0A,"",#FF,"ENEMY QUARRY.",#00
NEW_EQUIPMENT:
	db "NEW EQUIPMENT",#0A
	db "",#FE,"",#0A,"",#0A,"",#0A,"",#0A,"",#FE,"+2 QUARRY.",#00
STRIP_MINE:
	db "STRIP MINE",#0A
	db "",#0A,"",#09,"",#FF,"-1 QUARRY,",#0A,"",#0A,"",#09,"",#FE,"+10 WALL.",#0A,"",#0A,"YOU GAIN 5 GEMS.",#00
REINFORCED_WALL:
	db "REINFORCED WALL",#0A
	db "",#09,"+8 WALL.",#00
	endmodule