	module CARD_TEXT
map:
	dw BRICK_SHORTAGE
	dw LUCKY_CACHE
	dw FRIENDLY_TERRAIN
	dw MINERS

data:

BRICK_SHORTAGE:
	db "BRICK SHORTAGE",#0A
	db "ALL PLAYERS LOSE",#0A,"",#09,"8 BRICKS.",#00
LUCKY_CACHE:
	db "LUCKY CACHE",#0A
	db "+2 BRICKS, +2 GEMS, PLAY AGAIN.",#00
FRIENDLY_TERRAIN:
	db "FRIENDLY TERRAIN",#0A
	db "null",#00
MINERS:
	db "MINERS",#0A
	db "null",#00
	endmodule